version: '3'
services:
  rails:
    build: .
    command: rails s -b 0.0.0.0
    container_name: iugu_api_challenge
    ports:
      - 3000:3000
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=iugu_api_challenge_db
      - MYSQL_PORT=3306
      - MYSQL_HOST=db
    volumes:
      - .:/opt/app
    links:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=iugu_api_challenge_db
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - /var/lib/mysql
